Document: qtpass
Title: Debian qtpass Manual
Author: <insert document author here>
Abstract: This manual describes what qtpass is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qtpass/qtpass.sgml.gz

Format: postscript
Files: /usr/share/doc/qtpass/qtpass.ps.gz

Format: text
Files: /usr/share/doc/qtpass/qtpass.text.gz

Format: HTML
Index: /usr/share/doc/qtpass/html/index.html
Files: /usr/share/doc/qtpass/html/*.html
